# Generated by Django 3.2.3 on 2021-05-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasklist',
        ),
    ]
